name: Deploy to Cloudflare Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Build and Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NEXT_PUBLIC_WEB_URL: "https://manus.pages.dev"
          NEXT_PUBLIC_PROJECT_NAME: "ShipAny"
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXT_PUBLIC_PAY_SUCCESS_URL: "https://manus.pages.dev/my-orders"
          NEXT_PUBLIC_PAY_FAIL_URL: "https://manus.pages.dev/#pricing"
          NEXT_PUBLIC_PAY_CANCEL_URL: "https://manus.pages.dev/#pricing"
          NEXT_PUBLIC_LOCALE_DETECTION: "false"
          NEXT_PUBLIC_DEFAULT_THEME: "light"
        run: |
          pnpm build
          npx wrangler pages deploy .vercel/output/static --project-name=manus 